# Site settings
title: Claire Parker Pen
email: claire.parker87@gmail.com
description: Adventures in JavaScript web development
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.claireparker-pen.com" # the base hostname & protocol for your site
date_format: "%b %-d, %Y"
twitter_username: claireparkerpen
github_username:  claireparker

# How post URLs are settings
permalink: /blog/:title

# Build settings
markdown: kramdown

exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor', 'Procfile']

gems:
  - jemoji
  
# Post sharing icons
show_sharing_icons: false
# Change to 'true' to enable individual icons
share_facebook: false
share_twitter: false
share_googleplus: false
share_linkedin: false
share_digg: false
share_tumblr: false
share_reddit: false
share_stumbleupon: false
share_hackernews: false
# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname: 'claireparkerpen'
    
text:
  pagination:
    newer: 'Newer'
    older: 'Older'
  share_buttons:
    text:         'Share this post!'
    facebook:     'Share on Facebook'
    twitter:      'Share on Twitter'
    googleplus:   'Share on Google+'
    linkedin:     'Share on LinkedIn'
    digg:         'Share on Digg'
    tumblr:       'Share on Tumblr'
    reddit:       'Share on Reddit'
    stumbleupon:  'Share on StumbleUpon'
    hackernews:   'Share on Hacker News'
  post:
    updated:        'Updated'
    minute_read:    'minute read'
    related_posts:  'Related Posts'
  index:
    coming_soon: 'Coming soon...'
  contact:
    email:    'Email Address'
    content:  'What would you like to say?'
    subject:  'New submission!'
    submit:   'Say Hello'
    ajax:
      sending:  'sending..'
      sent:     'Message sent!'
      error:    'Error!'
  thanks: 'Thanks for contacting us. We will reply as soon as possible.'
  og_locale: 'en_US'
